stages:
  - raw
  - intermediate
  - primary
  - feature
  - models
  - model_selection

# Configuración común para todos los stages
.common_setup: &common_setup
  - apt-get update -y && apt-get install -y python3 python3-pip python3-venv
  - python3 -m venv proyecto_segmentacion
  - source proyecto_segmentacion/bin/activate
  - pip3 install --upgrade pip
  - pip3 install PyYAML==6.0.0
  - pip3 install pyarrow==16.1.0
  - pip3 install pandas==2.2.0

# Instalación específica para el stage de raw
.raw_setup: &raw_setup
  - *common_setup
  - pip3 install xlsx2csv==0.8.2
  - pip3 install openpyxl==3.1.0


## Ejecución de los stages

raw_pipeline:
  image: python:3.10.0
  stage: raw
  before_script:
    *raw_setup
  script:
    - echo "INICIO PIPELINE RAW"
    - proyecto_segmentacion/bin/python3 __main__.py 'raw_pipeline'
    - echo "FIN PIPELINE RAW"