name: proyecto_segmentacion
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pyarrow=15.0.0
  - mlflow=2.14.2
  - jupyter=1.0.0
  - ipykernel=6.29.0
  - sqlite=3.46.0
  - pandas=2.2.0
  - openpyxl=3.1.0
  - numpy=1.26.0
  - pyyaml=6.0.0
  - scikit-learn=1.5.0
  - bayesian-optimization=1.4.3
